### ISSUE TITLE
Service 'web' failed to build

### ISSUE THREAD

**Issue by ellyzing** [lucideus-repo/UnSAFE_Bank#7] opened 2020-10-19 09:38 UTC
$ docker-compose up -d
Building web
Step 1/12 : FROM node:alpine as build
 ---> fa2fa5d4e6f4
Step 2/12 : WORKDIR /app
 ---> Using cache
 ---> e25c8210dbba
Step 3/12 : COPY . /app
 ---> Using cache
 ---> 580e1e2cfd31
Step 4/12 : ENV PATH /app/node_modules/.bin:$PATH
 ---> Using cache
 ---> d5d559e29acd
Step 5/12 : RUN yarn -s
 ---> Running in da944c42d4db
warning @testing-library/jest-dom > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @testing-library/jest-dom > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated                                                                                                     
warning @testing-library/jest-dom > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated                                                                                                  
warning @testing-library/react > @types/testing-library__react > @types/testing-library__dom@7.5.0: This is a stub types definition. testing-library__dom provides its own type definitions, so you do not need this installed.     
warning @types/reactstrap > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1                                                                                          
warning @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!                                        
warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                                                                                                 
warning node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                                                                                      
warning node-sass > request > har-validator@5.1.5: this library is no longer supported                            
warning react-scripts > eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin    
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                                                   
warning react-scripts > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.                                                                                  
warning react-scripts > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.                                                            
warning react-scripts > babel-jest > @jest/transform > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.                                            
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142                                                                                                  
warning react-scripts > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.                                                           
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)                                      
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                            
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142                                                                           
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained                                                          
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained                                                         
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained                                                            
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained                                                            
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained                                               
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()                                                                                            
warning react-scripts > workbox-webpack-plugin > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.                     
warning reactstrap > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1                                                                                  
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/free-                              solid-svg-icons/-/free-solid-svg-icons-5.15.1.tgz: ESOCKETTIMEDOUT".                
ERROR: Service 'web' failed to build : The command '/bin/sh -c yarn -s' returned a non-zero code: 1

**Comment by DeepakPawar95** [comment] 2020-10-19 19:02
I think it's a temporary network issue, please check your network connection and try again later.
In case it won't work, try increasing the network timeout in .yarnrc file `yarn config set network-timeout 600000 -g`

**Comment by dspawar** [comment] 2021-03-16 06:20
Closing this issue as it's not application dependent.

**Closed by dspawar** 2021-03-16 06:20 UTC

**Comment by ZZerow** [comment] 2022-05-16 01:13
I had same issue, and in my case, it was out of the memory and  package version error. 
1. Make sure execute on SUDO mode.  
2. Check what makes error. 
-> You can see the cause by typing "sudo yarn build -s"in the directory(~/UnSAFE_Bank/Backend/web/).
