### ISSUE TITLE
Where is bank account number verified

### ISSUE THREAD

**Issue by mmesojedec** [lucideus-repo/UnSAFE_Bank#11] opened 2021-03-19 14:20 UTC
Hi,

Trying to change format of a bank account number, to actually use IBAN numbers.
I check "AddBeneficiaryPage.tsx", "Model_beneficiary.php" and some other pages, but can't figure it out where you are checking format of the bank account.

I corrected in the DB length of the account number to be max of 30 characters, and also changed some setting in .tsx and .php files.
Docker containers are build, but when I try to add new Beneficiary account, I'm getting error message that account number is not correct.

Any suggestion where I can quickly change this, so I can use more realistic bank accounts for EU?
IBAN looks like this (where length is from 16-30 characters): DE83500105173418298392

/Miha

**Comment by mmesojedec** [comment] 2021-03-24 17:36
Hi,

Would appreciate to get the answer, so i can modify details for account checking.

Miha

**Comment by DeepakPawar95** [comment] 2021-03-25 06:47
Hi @mmesojedec,

We don't recommend doing changes like these in the application. But if it's your requirement, then please refer to the below-mentioned files where the account numbers are checked and needs to be modified as per your need:

1. In the `Backend/mysql/db.sql` file, change the size of the `account_no` column in the `account_details` table from 12 to 16 (change the number as per your requirement). Then in the subsequent line in the `db.sql`, we are inserting 10-12 account details as data to be used by the application, so modify the account no in those as well.
2. In the `Backend/src/api/application/models/Model_beneficiary.php` file line 30, the `validate_add` function checks for the length of the account number received in the request to be 12 characters.
3. In the `Backend/src/api/application/models/Model_beneficiary.php` file line 210, the `add_ben` function checks if the account number provided in the request is valid and present in the UnSAFE Bank database or not.

The last step is to remove the current images and containers and rebuild the project again especially for the Backend and Database.

Best,
Deepak

**Comment by mmesojedec** [comment] 2021-03-25 11:25
Hi @DeepakPawar95 

I followed your steps and I still have same issue.

1. I changed db.sql to:

CREATE TABLE `account_details` (
  `id_pk` int NOT NULL AUTO_INCREMENT,
  `user_id_fk` int NOT NULL,
  `user_details_id_fk` int NOT NULL,
  `bank_master_id_fk` int NOT NULL,
  **`account_no` varchar(30) NOT NULL,**
  `account_balance` double NOT NULL,
  `income_tax_number` char(10) NOT NULL,

I also changed in the db.sql some of the account numbers (as you suggested) that are injected into the DB when containers are created, and this is working OK.

2. I changed in the "Model_beneficiary.php", length for the account, which can be from 12-30 characters including numbers and alphabet characters.  

        // account_number
        if (isset($data['data']['account_number'])) {
            if (!preg_match("/^[A-Za-z0-9]{12,30}$/", $data['data']['account_number'])) {
                return $status::IncorrectAcNoFormat;


I haven't disable checking for existing account numbers after line 210.


Even if i increase varchar to 255 in the db.sql, I'm getting same error.

Is there anything that is preventing to enter letters into the table, since IBAN format looks like "DE64500105171361678641"?
I'm asking because I can see "$all_chars" in the "Model_beneficiary.php" in the line 261.

**Comment by mmesojedec** [comment] 2021-03-25 15:41
Hi,

It's interesting that changes I created and mentioned in previous message are OK for displaying default Beneficiaries and also payment is done correctly.

Issue is only adding new beneficiary, since there is something wrong when format of the bank account_no is checked.

[
![Account_Statement](https://user-images.githubusercontent.com/80457709/112500349-96342300-8d88-11eb-9d27-22e2741a298a.png)
![Beneficiary](https://user-images.githubusercontent.com/80457709/112500354-96ccb980-8d88-11eb-8ba5-1c98729f1017.png)

](url)

**Comment by DeepakPawar95** [comment] 2021-03-25 16:13
Hi @mmesojedec,

The application support adding beneficiary only from the preloaded accounts which you can refer from here (https://github.com/lucideus-repo/UnSAFE_Bank#existing-user-bank-accounts) and it's also the part of line 48 in `db.sql` file. If you want to support new accounts, please add that entry in the db.sql file.

We have tested the same on our end and it's working with your suggested changes. Please don't forget to recreate your images and containers.

Best,
Deepak

**Comment by mmesojedec** [comment] 2021-03-26 06:15
Hi @DeepakPawar95,

Thank you for your feedback.
I missed somehow part that only preloaded accounts in the db.sql can be added.

Thought we can use any random number for account and add it to the DB.
You might close this ticket.

Thanks,
Miha

**Comment by dspawar** [comment] 2021-03-26 09:25
Closing this ticket as the issue is resolved.

**Closed by dspawar** 2021-03-26 09:25 UTC
